services:
  - type: web
    name: save-restricted-bot
    runtime: docker
    repo: https://github.com/medicosourav/Save-Restricted-Bot.git
    branch: main
    plan: free
    healthCheckPath: /
    envVars:
      - key: TOKEN
        sync: false
      - key: ID
        sync: false
      - key: HASH
        sync: false
      - key: STRING
        sync: false
